<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE snippets [
<!ELEMENT snippets (snippet)+>
<!ELEMENT snippet (title, language, ui, code)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT language (#PCDATA)>
<!ELEMENT ui (#PCDATA)>
<!ELEMENT code (#PCDATA)>
]>

<snippets>



  <snippet>
    <title>Main</title>
    <language>AutoIt</language>
    <ui>SAPGUI</ui>
    <code>
;-Begin-----------------------------------------------------------------

;-Directives------------------------------------------------------------
AutoItSetOption(&quot;MustDeclareVars&quot;, 1)

;-Sub Main--------------------------------------------------------------
Func Main()

  Local $SapGuiAuto, $application, $connection, $session

  $SapGuiAuto = ObjGet(&quot;SAPGUI&quot;)
  If Not IsObj($SapGuiAuto) Or @Error Then
    Return
  EndIf

  $application = $SapGuiAuto.GetScriptingEngine()
  If Not IsObj($application) Then
    Return
  EndIf

  $application.HistoryEnabled = False

  $connection = $application.Children(0)
  If Not IsObj($connection) Then
    Return
  EndIf

  If $connection.DisabledByServer = True Then
    Return
  EndIf

  $session = $connection.Children(0)
  If Not IsObj($session) Then
    Return
  EndIf

  If $session.Busy = True Then
    Return
  EndIf

  If $session.Info.IsLowSpeedConnection = True Then
    Return
  EndIf

  ;&gt;Insert your SAP GUI Scripting code here&lt;

  $application.HistoryEnabled = True

EndFunc

;-Main------------------------------------------------------------------
Main()

;-End-------------------------------------------------------------------
</code>
  </snippet>



  <snippet>
    <title>Main</title>
    <language>Java</language>
    <ui>Web</ui>
    <code>
//-Begin----------------------------------------------------------------

//-Import---------------------------------------------------------------
import java.util.HashMap;
import java.util.Map;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.*;

public class Selenium {

  public static void main(String[] args) {

    //-Set path to chromedriver-----------------------------------------
    System.setProperty(&quot;webdriver.chrome.driver&quot;,
      &quot;C:/Program Files/Selenium/chromedriver.exe&quot;);

    //-Set path to chrome browser---------------------------------------
    Map&lt;String, Object&gt; chromeOptions = new HashMap&lt;String, Object&gt;();
    chromeOptions.put(&quot;binary&quot;, &quot;C:/Program Files/Google/Chrome/Application/chrome.exe&quot;);
    DesiredCapabilities capabilities = DesiredCapabilities.chrome();
    capabilities.setCapability(ChromeOptions.CAPABILITY, chromeOptions);

    //-Opens a web browser window---------------------------------------
    WebDriver driver = new ChromeDriver(capabilities);

    //&gt;Insert your scripting code here&lt;

    driver.close();
    driver.quit();

    System.exit(0);

  }

}

//-End------------------------------------------------------------------
</code>
  </snippet>



  <snippet>
    <title>Main</title>
    <language>Java</language>
    <ui>SAPGUI</ui>
    <code>
//-Begin----------------------------------------------------------------

//-Classpath------------------------------------------------------------
/env -class-path C:\Tracker\jacob\jacob.jar

//-Import---------------------------------------------------------------
import com.jacob.activeX.*;
import com.jacob.com.*;

//-Sub Main-------------------------------------------------------------
void Main() {

  ActiveXComponent SAPROTWr, application, connection, session, Obj;
  Dispatch ROTEntry;
  Variant Value, ScriptEngine;
  Variant[] arg;
  boolean DisabledByServer, Busy, IsLowSpeedConnection;

  ComThread.InitSTA();

  application = null;

  //-Set SapGuiAuto = GetObject(&quot;SAPGUI&quot;)-------------------------------
  SAPROTWr = new ActiveXComponent(&quot;SapROTWr.SapROTWrapper&quot;);
  try {
    ROTEntry = SAPROTWr.invoke(&quot;GetROTEntry&quot;, &quot;SAPGUI&quot;).toDispatch();

    //-Set application = SapGuiAuto.GetScriptingEngine------------------
    ScriptEngine = Dispatch.call(ROTEntry, &quot;GetScriptingEngine&quot;);
    application = new ActiveXComponent(ScriptEngine.toDispatch());

    application.setProperty("HistoryEnabled", false);

    //-Set connection = application.Children(0)-------------------------
    connection = new ActiveXComponent(
      application.invoke(&quot;Children&quot;, 0).toDispatch()
    );

    DisabledByServer = connection.getProperty("DisabledByServer").changeType(Variant.VariantBoolean).getBoolean();
    if(DisabledByServer == true) {
      System.out.println("Scripting is disabled by server");
      //System.exit(1);
      return;
    }

    //-Set session = connection.Children(0)-----------------------------
    session = new ActiveXComponent(
      connection.invoke(&quot;Children&quot;, 0).toDispatch()
    );

    Busy = session.getProperty("Busy").changeType(Variant.VariantBoolean).getBoolean();
    if(Busy == true) {
      System.out.println("Session is busy");
      //System.exit(1);
      return;
    }

    IsLowSpeedConnection = session.getPropertyAsComponent("Info").getProperty("IsLowSpeedConnection").changeType(Variant.VariantBoolean).getBoolean();
    if(IsLowSpeedConnection == true) {
      System.out.println("Connection is low speed");
      //System.exit(1);
      return;
    }

    //&gt;Insert your SAP GUI Scripting code here&lt;

  } catch (Exception e) {
    System.out.println(e.getMessage().toString());
  }
  finally {
    application.setProperty("HistoryEnabled", true);
    ComThread.Release();
  }

}

//-Main-----------------------------------------------------------------
Main();
/exit

//-End------------------------------------------------------------------
</code>
  </snippet>



  <snippet>
    <title>Main</title>
    <language>PowerShell</language>
    <ui>Web</ui>
    <code>
#-Begin-----------------------------------------------------------------

#-Sub Main--------------------------------------------------------------
Function Main {

  $Url = &quot;&quot;
  Open $Url

  $script:wait = [OpenQA.Selenium.Support.UI.WebDriverWait]::new($script:driver, [System.TimeSpan]::FromSeconds(30));
  $script:action = [OpenQA.Selenium.Interactions.Actions]::new($script:driver);


  #&gt;Insert your code here&lt;


  $script:driver.Close();
  $script:driver.Quit();

  $script:action = $Null;
  $script:wait = $Null;
  $script:driver = $Null;

}

#-Main------------------------------------------------------------------
LoadSelenium;
Main;

#-End-------------------------------------------------------------------
</code>
  </snippet>



  <snippet>
    <title>Main</title>
    <language>PowerShell</language>
    <ui>SAPGUI</ui>
    <code>
#-Begin-----------------------------------------------------------------

#-Includes--------------------------------------------------------------
.&quot;$PSScriptRoot\COM.ps1&quot;

#-Sub Main--------------------------------------------------------------
Function Main {

  $SapGuiAuto = Get-Object &quot;SAPGUI&quot;;
  If ($SapGuiAuto -IsNot [System.__ComObject]) {
    Return;
  }

  $application = Invoke-Method $SapGuiAuto &quot;GetScriptingEngine&quot;;
  If ($application -IsNot [System.__ComObject]) {
    Free-Object -object $SapGuiAuto;
    Return;
  }

  Set-Property -object $application -propertyName "HistoryEnabled" -propertyParameter @($False);

  $connection = Get-Property $application &quot;Children&quot; @(0);
  If ($Null -eq $connection) {
    Free-Object -object $application;
    Free-Object -object $SapGuiAuto;
    Return;
  }

  $DisabledByServer = Get-Property $connection "DisabledByServer";
  If ($True -eq $DisabledByServer) {
    Return;
  }

  $session = Get-Property $connection &quot;Children&quot; @(0);
  If ($Null -eq $session) {
    Free-Object -object $connection;
    Free-Object -object $application;
    Free-Object -object $SapGuiAuto;
    Return;
  }

  $Busy = Get-Property $session "Busy";
  If ($True -eq $Busy) {
    Return;
  }

  $Info = Get-Property $session "Info";
  $IsLowSpeedConnection = Get-Property $Info "IsLowSpeedConnection";
  If ($True -eq $IsLowSpeedConnection) {
    Return;
  }

  #&gt;Insert your SAP GUI Scripting code here&lt;

  Set-Property -object $application -propertyName "HistoryEnabled" -propertyValue @($True);

  Free-Object -object $session;
  Free-Object -object $connection;
  Free-Object -object $application;
  Free-Object -object $SapGuiAuto;

}

#-Main------------------------------------------------------------------
Main

#-End-------------------------------------------------------------------
</code>
  </snippet>



  <snippet>
    <title>Main</title>
    <language>PowerShell</language>
    <ui>Mobile</ui>
    <code>
#-Begin-----------------------------------------------------------------

#-Sub Main--------------------------------------------------------------
Function Main {

  [OpenQA.Selenium.Remote.DesiredCapabilities]$Capabilities = `
    [OpenQA.Selenium.Remote.DesiredCapabilities]::new();
  $Capabilities.SetCapability([OpenQA.Selenium.Appium.Enums.MobileCapabilityType]::`
    DeviceName, &quot;emulator-5554&quot;);
  $Capabilities.SetCapability([OpenQA.Selenium.Appium.Enums.MobileCapabilityType]::`
    PlatformVersion, &quot;8.1.0&quot;);
  $Capabilities.SetCapability([OpenQA.Selenium.Appium.Enums.MobileCapabilityType]::`
    PlatformName, &quot;Android&quot;);
  $Capabilities.SetCapability([OpenQA.Selenium.Appium.Enums.AndroidMobileCapabilityType]::`
    AppPackage, &quot;com.android.calculator2&quot;);
  $Capabilities.SetCapability([OpenQA.Selenium.Appium.Enums.AndroidMobileCapabilityType]::`
    AppActivity, &quot;com.android.calculator2.Calculator&quot;);

  [System.Uri]$Uri = [System.Uri]::new(&quot;http://127.0.0.1:4723/wd/hub&quot;);

  $script:driver = `
    [OpenQA.Selenium.Appium.Android.AndroidDriver[OpenQA.Selenium.Appium.AppiumWebElement]]::`
    new($Uri, $Capabilities);
  If ($Null -eq $script:driver) {
    Return;
  }


  #&gt;Insert your code here&lt;


  $script:driver.CloseApp();
  $script:driver.Quit();

  $script:driver = $Null;

}

#-Main------------------------------------------------------------------
LoadAppium;
Main;

#-End-------------------------------------------------------------------
</code>
  </snippet>



  <snippet>
    <title>Main</title>
    <language>Python</language>
    <ui>SAPGUI</ui>
    <code>
#-Begin-----------------------------------------------------------------

#-Includes--------------------------------------------------------------
import sys, win32com.client

#-Sub Main--------------------------------------------------------------
def Main():

  try:

    SapGuiAuto = win32com.client.GetObject(&quot;SAPGUI&quot;)
    if not type(SapGuiAuto) == win32com.client.CDispatch:
      return

    application = SapGuiAuto.GetScriptingEngine
    if not type(application) == win32com.client.CDispatch:
      SapGuiAuto = None
      return

    application.HistoryEnabled = False

    connection = application.Children(0)
    if not type(connection) == win32com.client.CDispatch:
      application = None
      SapGuiAuto = None
      return

    if connection.DisabledByServer == True:
      connection = None
      application = None
      SapGuiAuto = None
      return

    session = connection.Children(0)
    if not type(session) == win32com.client.CDispatch:
      connection = None
      application = None
      SapGuiAuto = None
      return

    if session.Busy == True:
      session = None
      connection = None
      application = None
      SapGuiAuto = None
      return

    if session.Info.IsLowSpeedConnection == True:
      session = None
      connection = None
      application = None
      SapGuiAuto = None
      return

    #&gt;Insert your SAP GUI Scripting code here&lt;

  except:
    print(sys.exc_info()[0])

  finally:
    application.HistoryEnabled = True
    session = None
    connection = None
    application = None
    SapGuiAuto = None

#-Main------------------------------------------------------------------
Main()

#-End-------------------------------------------------------------------
</code>
  </snippet>



  <snippet>
    <title>Main</title>
    <language>WScript</language>
    <ui>SAPGUI</ui>
    <code>
&apos;-Begin-----------------------------------------------------------------

&apos;-Directives------------------------------------------------------------
Option Explicit

&apos;-Sub Main--------------------------------------------------------------
Sub Main()

  Dim SapGuiAuto, app, connection, session

  Set SapGuiAuto = GetObject(&quot;SAPGUI&quot;)
  If Not IsObject(SapGuiAuto) Then
    Exit Sub
  End If

  Set app = SapGuiAuto.GetScriptingEngine
  If Not IsObject(app) Then
    Exit Sub
  End If

  app.HistoryEnabled = False

  Set connection = app.Children(0)
  If Not IsObject(connection) Then
    Exit Sub
  End If

  If connection.DisabledByServer = True Then
    Exit Sub
  End If

  Set session = connection.Children(0)
  If Not IsObject(session) Then
    Exit Sub
  End If

  If session.Busy = True Then
    Exit Sub
  End If

  If session.Info.IsLowSpeedConnection = True Then
    Exit Sub
  End If

  &apos;&gt;Insert your SAP GUI Scripting code here&lt;

  app.HistoryEnabled = True

End Sub

&apos;-Main------------------------------------------------------------------
Main

&apos;-End-------------------------------------------------------------------
</code>
  </snippet>



  <snippet>
    <title>Wait until keypressed</title>
    <language>PowerShell</language>
    <ui>All</ui>
    <code>
[Void][Console]::WriteLine(&quot;Press key...&quot;);
[Void][Console]::ReadKey(&quot;NoEcho,IncludeKeyDown&quot;);
</code>
  </snippet>



  <snippet>
    <title>Wait until keypressed</title>
    <language>Python</language>
    <ui>All</ui>
    <code>
    input(&quot;Press key...&quot;)
</code>
  </snippet>



  <snippet>
    <title>Sleep</title>
    <language>AutoIt</language>
    <ui>All</ui>
    <code>
  Sleep(1000)
</code>
  </snippet>



  <snippet>
    <title>Sleep</title>
    <language>Java</language>
    <ui>All</ui>
    <code>
  Thread.sleep(1000);
</code>
  </snippet>



  <snippet>
    <title>Sleep</title>
    <language>PowerShell</language>
    <ui>All</ui>
    <code>
  Start-Sleep -Milliseconds 1000;
</code>
  </snippet>



  <snippet>
    <title>Sleep</title>
    <language>Python</language>
    <ui>All</ui>
    <code>
    import time
    time.sleep(5)
</code>
  </snippet>



  <snippet>
    <title>Sleep</title>
    <language>WScript</language>
    <ui>All</ui>
    <code>
  WScript.Sleep 1000
</code>
  </snippet>



  <snippet>
    <title>Sub Sleep</title>
    <language>WScript</language>
    <ui>All</ui>
    <code>
&apos;-Sub Sleep-------------------------------------------------------------
Sub Sleep(MilliSecondsToWait)

  Dim WshShell

  If Not IsNumeric(MilliSecondsToWait) Then
    Exit Sub
  End If

  Set WshShell = CreateObject(&quot;WScript.Shell&quot;)
  WshShell.Run &quot;%COMSPEC% /c ping -n 1 -w &quot; &amp; _
    CStr(MilliSecondsToWait) &amp; &quot; 127.255.255.254 > nul&quot;, 0, True

End Sub
</code>
  </snippet>



  <snippet>
    <title>MessageBox</title>
    <language>PowerShell</language>
    <ui>All</ui>
    <code>
[Void][System.Windows.Forms.MessageBox]::Show(&quot;Text&quot;, &quot;Caption&quot;, [System.Windows.Forms.MessageBoxButtons]::OK);
</code>
  </snippet>



  <snippet>
    <title>MessageBox</title>
    <language>Java</language>
    <ui>All</ui>
    <code>
JOptionPane.showMessageDialog(null, "Text", "Caption", JOptionPane.PLAIN_MESSAGE);
</code>
  </snippet>



  <snippet>
    <title>WinAPI</title>
    <language>PowerShell</language>
    <ui>All</ui>
    <code>
Add-Type @&quot;

  using System;
  using System.Runtime.InteropServices;

  public class WinAPI {

    //-SetForegroundWindow----------------------------------------------
    [DllImport(&quot;user32.dll&quot;)]
      [return: MarshalAs(UnmanagedType.Bool)]
      public static extern bool SetForegroundWindow(IntPtr hWnd);

    //-FindWindow-------------------------------------------------------
    [DllImport(&quot;user32.dll&quot;, CharSet = CharSet.Auto)]
      public static extern IntPtr FindWindow(string lpClassName, string lpWindowName);

    //-OutputDebugString------------------------------------------------
    [DllImport(&quot;kernel32.dll&quot;)]
    public static extern void OutputDebugString(string lpOutputString);

}

&quot;@


  $hWin = [WinAPI]::FindWindow(&quot;Notepad&quot;, &quot;Unbenannt - Editor&quot;);
  [WinAPI]::SetForegroundWindow($hWin);
  [WinAPI]::OutputDebugString(&quot;Notepad&quot;);
</code>
  </snippet>



  <snippet>
    <title>Sub DebugPrint</title>
    <language>AutoIt</language>
    <ui>All</ui>
    <code>
;-Sub DebugPrint--------------------------------------------------------
Func DebugPrint

Param(
  $Message
)

  $Message = String($Message)
  DLLCall(&quot;kernel32.dll&quot;, &quot;none&quot;, &quot;OutputDebugString&quot;, &quot;str&quot;, _
    $Message)
EndFunc
</code>
  </snippet>



  <snippet>
    <title>Function DebugPrint</title>
    <language>PowerShell</language>
    <ui>All</ui>
    <code>
#-Sub DebugPrint--------------------------------------------------------
Function DebugPrint {

  Param(
    [String]$Message,
    [String]$Category = &quot;&quot;
  )

  If ($Category -eq &quot;&quot;) {
    [System.Diagnostics.Debug]::WriteLine($Message);
  } Else {
    [System.Diagnostics.Debug]::WriteLine($Message, $Category);
  }
}
</code>
  </snippet>



  <snippet>
    <title>ClipBoard</title>
    <language>PowerShell</language>
    <ui>All</ui>
    <code>
&quot;This is a test`r`nThis is a test&quot; | Set-Clipboard;
$Text = [Windows.Clipboard]::GetText();
Write-Host $Text;
</code>
  </snippet>



  <snippet>
    <title>ClipBoard</title>
    <language>WScript</language>
    <ui>All</ui>
    <code>
Set oIE = CreateObject(&quot;InternetExplorer.Application&quot;)
oIE.Navigate(&quot;about:blank&quot;)
oIE.document.parentwindow.clipboardData.SetData &quot;text&quot;, &quot;Your text here&quot;
Result = oIE.document.parentwindow.clipboardData.GetData(&quot;text&quot;)
MsgBox Result
oIE.document.parentwindow.clipboardData.ClearData()
oIE.Quit
</code>
  </snippet>



  <snippet>
    <title>AutoItX</title>
    <language>PowerShell</language>
    <ui>All</ui>
    <code>
#-Includes AutoItX------------------------------------------------------
Add-Type -Path &quot;$($PSScriptRoot)\AutoItX\AutoItX3.Assembly.dll&quot;;
Import-Module &quot;$PSScriptRoot\AutoItX\AutoItX.psd1&quot;;
</code>
  </snippet>



  <snippet>
    <title>GetOSLanguage</title>
    <language>PowerShell</language>
    <ui>All</ui>
    <code>
#$CultList = [System.Globalization.CultureInfo]::GetCultures(&apos;InstalledWin32Cultures&apos;);
#$CultList | Out-Gridview -Title &quot;InstalledWin32Cultures&quot;;

Switch((Get-Culture).TwoLetterISOLanguageName) {
  &quot;de&quot; {
    Write-Host &quot;de (Deutsch)&quot;;
  }
  &quot;en&quot; {
    Write-Host &quot;en (English)&quot;;
  }
  Default {
    Write-Host &quot;Your Language Code is&quot; `
    (Get-Culture).TwoLetterISOLanguageName;
  }
}

Switch((Get-Culture).Name) {
  &quot;de-DE&quot; {
    Write-Host &quot;Deutsch - Deutschland&quot;;
  }
  &quot;en-AU&quot; {
    Write-Host &quot;English - Australia&quot;;
  }
  Default {
    Write-Host &quot;Your Region is&quot; `
    (Get-Culture).Name;
  }
}

Switch((Get-Culture).KeyboardLayoutId) {
  1031 {
    Write-Host &quot;Keyboard Layout ID is 1031&quot;;
  }
  Default {
    Write-Host &quot;Your Keyboard Layout ID is&quot; `
    (Get-Culture).KeyboardLayoutId;
  }
}
</code>
  </snippet>



  <snippet>
    <title>Function Check</title>
    <language>WScript</language>
    <ui>SAPGUI</ui>
    <code>
&apos;-Function Check--------------------------------------------------------
&apos;-
&apos;- Checks if a control exists and delivers true, otherwise false
&apos;-
&apos;-----------------------------------------------------------------------
Function Check(Session, Ctrl)

  Dim Result

  On Error Resume Next
  Session.findById(Ctrl)
  If Err.Number &lt;&gt; 0 Then
    Result = vbFalse
  Else
    Result = vbTrue
  End If
  On Error Goto 0
  Err.Clear
  Check = Result

End Function
</code>
  </snippet>



  <snippet>
    <title>Function FindAllByType</title>
    <language>WScript</language>
    <ui>SAPGUI</ui>
    <code>
  Dim gColl()

&apos;-Function FindAllByType------------------------------------------------
&apos;-
&apos;- Delivers of the given object an array of objects of one type
&apos;-
&apos;- Example:
&apos;- Dim Coll
&apos;- Coll = FindAllByType(session, &quot;GuiLabel&quot;)
&apos;-
&apos;-----------------------------------------------------------------------
Function FindAllByType(Obj, strType)

  Dim cntObj, i, j, Child

  On Error Resume Next
  cntObj = Obj.Children.Count()
  If cntObj &gt; 0 Then
    For i = 0 To cntObj - 1
      Set Child = Obj.Children.Item(CLng(i))
      FindAllByType Child, strType
      If UCase(Child.Type()) = UCase(strType) Then
        ReDim Preserve gColl(j)
        Set gColl(j) = Child
        j = j + 1
      End If
    Next
  End If
  On Error Goto 0
  FindAllByType = gColl

End Function
</code>
  </snippet>



  <snippet>
    <title>Function FindAllByTypeEx</title>
    <language>WScript</language>
    <ui>SAPGUI</ui>
    <code>
  Dim gColl()

&apos;-Function FindAllByTypeEx----------------------------------------------
&apos;-
&apos;- Delivers of the given object an array of objects of one type
&apos;-
&apos;- Example:
&apos;- Dim Coll
&apos;- Coll = FindAllByTypeEx(session, 30) &apos;GuiLabel
&apos;-
&apos;-----------------------------------------------------------------------
Function FindAllByTypeEx(Obj, lngType)

  Dim cntObj, i, j, Child

  On Error Resume Next
  cntObj = Obj.Children.Count()
  If cntObj &gt; 0 Then
    For i = 0 To cntObj - 1
      Set Child = Obj.Children.Item(CLng(i))
      FindAllByTypeEx Child, lngType
      If Child.TypeAsNumber() = lngType Then
        ReDim Preserve gColl(j)
        Set gColl(j) = Child
        j = j + 1
      End If
    Next
  End If
  On Error Goto 0
  FindAllByTypeEx = gColl

End Function
</code>
  </snippet>



  <snippet>
    <title>Function GetGridAsText</title>
    <language>WScript</language>
    <ui>SAPGUI</ui>
    <code>
&apos;-Function GetGridAsText------------------------------------------------
Function GetGridAsText(Grid)

  Dim Columns, i, j, Text

  Set Columns = Grid.ColumnOrder()

  For i = 0 To Grid.RowCount() - 1
    For j = 0 To Grid.ColumnCount() - 1
      If j = 0 Then
        Text = Text &amp; Grid.GetCellValue(i, CStr(Columns(j)))
      ElseIf j &gt; 0 And j &lt; Grid.ColumnCount() - 1 Then
        Text = Text &amp; &quot;;&quot; &amp; Grid.GetCellValue(i, CStr(Columns(j)))
      ElseIf j = Grid.ColumnCount() - 1 Then
        Text = Text &amp; &quot;;&quot; &amp; Grid.GetCellValue(i, CStr(Columns(j))) &amp; _
          vbCrLf
      End If
    Next
    If i Mod 32 = 0 Then
      Grid.SetCurrentCell i, CStr(Columns(0))
    End If
  Next

  GetGridAsText = Text

End Function
</code>
  </snippet>



  <snippet>
    <title>Function GetGridAsText</title>
    <language>AutoIt</language>
    <ui>SAPGUI</ui>
    <code>
;-Function GetGridAsText------------------------------------------------
Func GetGridAsText($Grid)

  Local $Columns, $i, $j, $Text

  $Columns = $Grid.ColumnOrder()

  For $i = 0 To $Grid.RowCount() - 1
    For $j = 0 To $Grid.ColumnCount() - 1
      If $j = 0 Then
        $Text = $Text &amp; $Grid.GetCellValue($i, $Columns($j))
      ElseIf $j &gt; 0 And $j &lt; $Grid.ColumnCount() - 1 Then
        $Text = $Text &amp; &quot;;&quot; &amp; $Grid.GetCellValue($i, $Columns($j))
      ElseIf $j = $Grid.ColumnCount() - 1 Then
        $Text = $Text &amp; &quot;;&quot; &amp; $Grid.GetCellValue($i, _
          $Columns($j)) &amp; @CRLF
      EndIf
    Next
    If Mod($i, 32) = 0 Then
      $Grid.SetCurrentCell($i, $Columns(0))
    EndIf
  Next

  Return $Text

EndFunc
</code>
  </snippet>



  <snippet>
    <title>Sub GetInfo (Host)</title>
    <language>PowerShell</language>
    <ui>SAPGUI</ui>
    <code>
#-Function GetInfo------------------------------------------------------
#-
#- Writes information about the given session on the console
#-
#- Example:
#- GetInfo $session
#-
#-----------------------------------------------------------------------
Function GetInfo {

  Param(
    [System.__ComObject]$session
  )

  $Info = Get-Property $session &quot;Info&quot;;
  If ($Info -is [System.__ComObject]) {
    $Transaction = Get-Property $Info &quot;Transaction&quot;;
    Write-Host &quot;Tansaction:  &quot; $Transaction;
    $Program = Get-Property $Info &quot;Program&quot;;
    Write-Host &quot;Program:     &quot; $Program;
    $ScreenNumber = Get-Property $Info &quot;ScreenNumber&quot;;
    Write-Host &quot;ScreenNumber:&quot; $ScreenNumber;
    $CodePage = Get-Property $Info &quot;CodePage&quot;;
    Write-Host &quot;CodePage:    &quot; $CodePage;
    $GuiCodePage = Get-Property $Info &quot;GuiCodePage&quot;;
    Write-Host &quot;GuiCodePage: &quot; $GuiCodePage;
    $I18NMode = Get-Property $Info &quot;I18NMode&quot;;
    Write-Host &quot;I18NMode:    &quot; $I18NMode;
    $Language = Get-Property $Info &quot;Language&quot;;
    Write-Host &quot;Language:    &quot; $Language;
    $IsLowSpeed = Get-Property $Info &quot;IsLowSpeedConnection&quot;;
    Write-Host &quot;IsLowSpeed:  &quot; $IsLowSpeed;
  }

}
</code>
  </snippet>



  <snippet>
    <title>Sub GetInfo (File)</title>
    <language>PowerShell</language>
    <ui>SAPGUI</ui>
    <code>
#-Function GetInfo------------------------------------------------------
#-
#- Writes information about the given session in a file
#-
#- Example:
#- GetInfo $session &quot;C:\Dummy\Info.txt&quot;
#-
#---------------------------------------------------------------------
Function GetInfo {

  Param (
    [System.__ComObject]$session,
    [String]$FileName
  )

  $Info = Get-Property $session &quot;Info&quot;;
  If ($Info -is [System.__ComObject]) {
    $Transaction = Get-Property $Info &quot;Transaction&quot;;
    $Text = &quot;Tansaction:   &quot; + $Transaction;
    $Text | Set-Content $FileName;
    $Program = Get-Property $Info &quot;Program&quot;;
    $Text = &quot;Program:      &quot; + $Program;
    $Text | Add-Content $FileName;
    $ScreenNumber = Get-Property $Info &quot;ScreenNumber&quot;;
    $Text = &quot;ScreenNumber: &quot; + $ScreenNumber;
    $Text | Add-Content $FileName;
    $CodePage = Get-Property $Info &quot;CodePage&quot;;
    $Text = &quot;CodePage:     &quot; + $CodePage;
    $Text | Add-Content $FileName;
    $GuiCodePage = Get-Property $Info &quot;GuiCodePage&quot;;
    $Text = &quot;GuiCodePage:  &quot; + $GuiCodePage;
    $Text | Add-Content $FileName;
    $I18NMode = Get-Property $Info &quot;I18NMode&quot;;
    $Text = &quot;I18NMode:     &quot; + $I18NMode;
    $Text | Add-Content $FileName;
    $Language = Get-Property $Info &quot;Language&quot;;
    $Text = &quot;Language:     &quot; + $Language;
    $Text | Add-Content $FileName;
    $IsLowSpeed = Get-Property $Info &quot;IsLowSpeedConnection&quot;;
    $Text = &quot;IsLowSpeed:   &quot; + $IsLowSpeed;
    $Text | Add-Content $FileName;
  }

}
</code>
  </snippet>



  <snippet>
    <title>Sub GetInfo</title>
    <language>WScript</language>
    <ui>SAPGUI</ui>
    <code>
&apos;-Sub GetInfo-----------------------------------------------------------
&apos;-
&apos;- Writes information about the given session in a file
&apos;-
&apos;- Example:
&apos;- GetInfo(session, &quot;C:\Dummy\Info.txt&quot;)
&apos;-
&apos;-----------------------------------------------------------------------
Sub GetInfo(session, FileName)

  Dim info, oFSO, oFile

  Set info = session.Info

  Set oFSO=CreateObject(&quot;Scripting.FileSystemObject&quot;)
  Set oFile = oFSO.CreateTextFile(FileName, True)
  oFile.Write &quot;Transaction          : &quot; &amp; _
    Info.Transaction &amp; vbCrLf
  oFile.Write &quot;Program              : &quot; &amp; _
  Info.Program &amp; vbCrLf
  oFile.Write &quot;ScreenNumber         : &quot; &amp; _
    CStr(Info.ScreenNumber) &amp; vbCrLf
  oFile.Write &quot;CodePage             : &quot; &amp; _
    CStr(Info.CodePage) &amp; vbCrLf
  oFile.Write &quot;GuiCodePage          : &quot; &amp; _
    CStr(Info.GuiCodePage) &amp; vbCrLf
  oFile.Write &quot;I18NMode             : &quot; &amp; _
    CStr(Info.I18NMode) &amp; vbCrLf
  oFile.Write &quot;Language             : &quot; &amp; _
    CStr(Info.Language) &amp; vbCrLf
  oFile.Write &quot;IsLowSpeedConnection : &quot; &amp; _
    CStr(Info.IsLowSpeedConnection) &amp; vbCrLf
  oFile.Close

End Sub
</code>
  </snippet>



  <snippet>
    <title>Sub GetInfo</title>
    <language>AutoIt</language>
    <ui>SAPGUI</ui>
    <code>
;-Includes--------------------------------------------------------------
  #Include &lt;FileConstants.au3&gt;

;-Sub GetInfo-----------------------------------------------------------
;-
;- Writes information about the given session in a file
;-
;- Example:
;- GetInfo($Session, &quot;C:\Dummy\Info.txt&quot;)
;-
;-----------------------------------------------------------------------
Func GetInfo($Session, $FileName)

  Local $Info, $hFile

  $Info = $Session.Info()

  $hFile = FileOpen($FileName, $FO_OVERWRITE)
  If $hFile = -1 Then
    Return
  EndIf
  FileWriteLine($hFile, &quot;Transaction          : &quot; &amp; _
    $Info.Transaction())
  FileWriteLine($hFile, &quot;Program              : &quot; &amp; _
    $Info.Program())
  FileWriteLine($hFile, &quot;ScreenNumber         : &quot; &amp; _
    $Info.ScreenNumber())
  FileWriteLine($hFile, &quot;CodePage             : &quot; &amp; _
    $Info.CodePage())
  FileWriteLine($hFile, &quot;GuiCodePage          : &quot; &amp; _